<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SistemaPedidosD_G.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\" />
    <Folder Include="Enums\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

</Project>
