// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPedidosD_G.Infrastructure.Persistence;
using SistemaPedidosD_G.Domain.Aggregates;

#nullable disable

namespace SistemaPedidosD_G.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaPedidosDGDbContext))]
    partial class SistemaPedidosDGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Carrito", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClienteId");

                    b.ToTable("Carritos", (string)null);
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.HistorialPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("HistorialPedidos", (string)null);
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoEntrega")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Repartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Repartidores", (string)null);
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Carrito", b =>
                {
                    b.OwnsMany("SistemaPedidosD_G.Domain.Entities.ItemCarrito", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<string>("ClienteId")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("NombreProducto")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ClienteId");

                            b1.ToTable("ItemsCarrito", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.HistorialPedido", b =>
                {
                    b.HasOne("SistemaPedidosD_G.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Pedido", b =>
                {
                    b.OwnsMany("SistemaPedidosD_G.Domain.Entities.DetallePedido", "Detalles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<string>("NombreProducto")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("DetallesPedido", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("SistemaPedidosD_G.Domain.ValueObjects.Dinero", "PrecioUnitario", b2 =>
                                {
                                    b2.Property<Guid>("DetallePedidoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Moneda")
                                        .IsRequired()
                                        .HasMaxLength(5)
                                        .HasColumnType("nvarchar(5)")
                                        .HasColumnName("Moneda");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecioUnitario");

                                    b2.HasKey("DetallePedidoId");

                                    b2.ToTable("DetallesPedido");

                                    b2.WithOwner()
                                        .HasForeignKey("DetallePedidoId");
                                });

                            b1.Navigation("PrecioUnitario")
                                .IsRequired();
                        });

                    b.OwnsOne("SistemaPedidosD_G.Domain.ValueObjects.Telefono", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsOne("SistemaPedidosD_G.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Direccion_Calle");

                            b1.Property<string>("Referencia")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Direccion_Referencia");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Direccion_Sector");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsOne("SistemaPedidosD_G.Domain.ValueObjects.NumeroPedido", "NumeroPedido", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NumeroPedido");

                            b1.HasKey("PedidoId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("Detalles");

                    b.Navigation("Direccion");

                    b.Navigation("NumeroPedido")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Repartidor", b =>
                {
                    b.OwnsOne("SistemaPedidosD_G.Domain.ValueObjects.Telefono", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("RepartidorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono");

                            b1.HasKey("RepartidorId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Repartidores");

                            b1.WithOwner()
                                .HasForeignKey("RepartidorId");
                        });

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPedidosD_G.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
