<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SistemaPedidosD_G.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\UseCases\" />
    <Folder Include="Contracts\Services\" />
    <Folder Include="Contracts\Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaPedidosD&amp;G.Domain\SistemaPedidosD&amp;G.Domain.csproj" />
  </ItemGroup>

</Project>
